# Generated by Django 2.0.6 on 2018-06-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telephone',
            field=models.CharField(max_length=99, unique=True),
        ),
    ]
