# Generated by Django 2.0.6 on 2018-06-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180628_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telephone',
            field=models.IntegerField(max_length=99, unique=True),
        ),
    ]
